---
- name: Create Environments for Entire Software Development Lifecycle
  hosts: local
  vars_files:
    - variables/microservices-vars.yml
    - variables/libraries-vars.yml
    - variables/cloud-environments-vars.yml
    - variables/boost-console-microservices-vars.yml    
  tasks:  
    - include: roles/init.yml    
    - include: roles/cicd-namespace.yml    
    - include: roles/build-namespace.yml
    - include: roles/test-namespace.yml
    - include: roles/monitoring-namespace.yml
    - include: roles/mq-green-namespace.yml
    - include: roles/mq-blue-namespace.yml
    - include: roles/prod-namespace.yml
