---
- name: Install Local Environment
  hosts: local 
  tasks:          
    - include_role:
        name: local-environment-setup    
      vars:
        test: false
        local_project: "microservices-scrum"
