---
- name: Run the build pipelines and then the release pipelines
  hosts: all
  vars_files:
    - microservices-vars.yml
    - pipelines-vars.yml
    
  tasks:  
    - name: Login in OpenShift as {{ username }}
      shell: "oc login --insecure-skip-tls-verify=true -u {{ username }} -p {{ password }} {{ openshift }}"
      tags:
        - openshift

    - name: Execute the release pipeline for each microservice
      shell: "oc start-build release-{{item.name }} --wait=true -n cicd"      
      with_items: "{{ microservices_scrum_projects }}"
      register: command_result
      failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
      changed_when: "'exists' not in command_result.stderr"      
      tags:
        - openshift              
        