---
# Define the name and description of the OpenShift project
- set_fact: project="build"
- set_fact: project_description="Build Environment for Microservices Scrum"

- include: namespace-setup.yml
- include: add-namespace-edit-role.yml
- include: amq-cloud-setup.yml
- include: external-db.yml
- include: wiremock-setup.yml
- include: add-jenkins-role.yml

  