---
- name: include the variables for this microservice      
  include_vars:
    file: "{{ workdir }}/{{ repo }}/ansible/microservice-vars.yml"  

- include: "{{ workdir }}/{{ repo }}/ansible/service-envs-{{ project }}-vars.yml"  

- include: pre-create-app.yml

- name: Create the microservices application from the source to image builder for application
  shell: 'oc new-app redhat-openjdk18-openshift:1.2~https://github.com/{{ github }}/{{ repo }}#{{ branch }} --name={{ microservice }} {{ service_envs }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift         

- include: post-create-app.yml
        