---
- name: Deploy the microservice for ({{ microservice }})
  shell: 'oc new-app redhat-openjdk18-openshift:1.4~https://github.com/{{ github }}/{{ repo }}.git --name={{ microservice }} -e OPENSHIFT_HOST_PORT={{ openshift }} -e OPENSHIFT_USER={{ username }} -e OPENSHIFT_PASSWORD={{ password }} {{ service_envs }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift         

- name: Expose Service ({{ microservice }})
  shell: "oc expose service {{ microservice }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

- name: Configure the resource limits for microservice ({{ microservice }})
  shell: "oc set resources dc {{ microservice }} -c={{ microservice }} --limits=cpu={{ cpu_max }},memory={{ memory_max }} --requests=cpu={{ cpu_min }},memory={{ memory_min }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

- name: Wait for the microservice to become available ({{ microservice }})
  shell : "oc rollout status dc/{{ microservice }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

        