---
- name: Checkout xpaas image stream from Github
  git:
    repo: "https://github.com/openshift/openshift-ansible.git"
    dest: "{{ workdir }}/openshift-ansible"
    version: openshift-ansible-3.9.27-1
    update: yes
  tags:
    - git  
    
- name: Install xpaas image streams
  shell: "oc create -f {{ workdir }}/openshift-ansible/roles/openshift_examples/files/examples/v3.9/xpaas-streams/jboss-image-streams.json -n {{ project }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - xpaas 
      
- name: Install xpaas source to image templates
  shell: "oc create -f {{ workdir }}/openshift-ansible/roles/openshift_examples/files/examples/v3.9/xpaas-templates -n {{ project }}"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - xpaas  
   

