---
# Define the name and description of the OpenShift project
- set_fact: project="monitoring"
- set_fact: project_description="Monitoring - Microservices Scrum"
    
- include: namespace-setup.yml
- include: add-namespace-view-role
- include: jaeger-setup.yml
- include: pgadmin-setup.yml
- include: boost-console-setup.yml

