---
# Define the name and description of the OpenShift project
- set_fact: project="mq-blue"
- set_fact: project_description="MQ Blue - Microservices Scrum"
    
- include: namespace-setup.yml
- include: amq-setup.yml
