---
# Define the name and description of the OpenShift project
- set_fact: project="mq-green"
- set_fact: project_description="MQ Green - Microservices Scrum"
    
- include: namespace-setup.yml
- include: imagestream-setup.yml
- include: amq-setup.yml

