---
- name: Create a new Openshift {{ project }}
  shell: "oc new-project {{ project }} --display-name='{{ project_description }}'"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
        
- name: Switch to Namespace {{ project }}
  shell: "oc project {{ project }}"
  tags:
    - openshift  

- name: Label the namespace as test passed is false
  shell: 'oc label namespace {{ project }} test-passed=false --overwrite=true'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
   



