---
# Define the name and description of the OpenShift project
- set_fact: project="test"
- set_fact: project_description="Test - Microservices Scrum"
    
- include: namespace-setup.yml
- include: add-namespace-edit-role
- include: amq-setup.yml
- include: jaeger-setup.yml
- include: external-db.yml
- include: add-jenkins-role.yml

