---
# the Absolute path where you want to checkout the sourcecode
workdir: "{{ ansible_env.HOME }}/.estafet"

# Your OpenShift credentials
username: developer
password: developer

# Does the use an external db
external_db: true

# Uncomment the following line to adjust the SCC (not using CDK3/minishift)
adjust_scc: false

# Define the name of the OpenShift project
project: prod

# Project Description
project_description: "Production Environment for Microservices Scrum"

# defines the location of the estafet github (change this if you have forked and want to use another github)
github: https://github.com/Estafet-LTD

# specify whether to remove the readiness probe for amq - this is a workaround for an issue with oc cluster up on windows
remove_amq_readiness: true

# expose basic ui
expose_basic_ui: true  

# enable readiness probe
readiness_probe: false

# amq url used for local environments
amq_url: tcp://broker-amq-tcp.prod.svc:61616

# test environment flag
test_environment: false