---
- name: include the variables for this microservice      
  include_vars:
    file: "{{ workdir }}/{{ repo }}/ansible/microservice-vars.yml"  

- include: "{{ workdir }}/{{ repo }}/ansible/service-envs-{{ project }}-vars.yml"  

- include: pre-create-app.yml

- name: Create the microservices application from the source to image builder for db application
  shell: 'oc new-app redhat-openjdk18-openshift:1.2~{{ github }}/{{ repo }}#{{ branch }} --name={{ microservice }} -e {{ db_url_env }}=jdbc:postgresql://postgresql.{{ project }}.svc:5432/{{ project }}-{{ microservice }} -e {{ db_user_env }}=postgres -e {{ db_db_env }}=welcome1 -e JBOSS_A_MQ_BROKER_URL={{ amq_url }} -e JBOSS_A_MQ_BROKER_USER={{ broker_pod_user }} -e JBOSS_A_MQ_BROKER_PASSWORD={{ broker_pod_password }} {{ service_envs }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift         

- include: post-create-app.yml
         