---
- name: Verify if variables are set
  fail:
    msg: "[Target directory] and/or [OpenShift host] is not defined. Please edit vars.yml"
  when: (workdir is undefined) or (openshift is undefined)

- name: Login in OpenShift as {{ username }}
  shell: "oc login --insecure-skip-tls-verify=true -u {{ username }} -p {{ password }} {{ openshift }}"
  tags:
    - openshift

- name: Adjust SCC
  shell: "oc patch scc restricted -p '{\"runAsUser\":{\"type\":\"RunAsAny\"}}'"
  when: adjust_scc

- name: Create Workdir
  file:
    path: "{{ workdir }}"
    state: directory

- name: Checkout source code from Github
  git:
    repo: "{{ github }}/{{ item.repo }}"
    dest: "{{ workdir }}/{{ item.repo }}"
    update: yes
  with_items: "{{ microservices_scrum_projects }}"
  tags:
    - git

- name: Checkout xpaas image stream from Github
  git:
    repo: "https://github.com/openshift/openshift-ansible.git"
    dest: "{{ workdir }}/openshift-ansible"
    version: openshift-ansible-3.9.27-1
    update: yes
  tags:
    - git  


    