---
# the Absolute path where you want to checkout the sourcecode
workdir: "{{ ansible_env.HOME }}/.estafet"

# Your OpenShift credentials
username: admin
password: 123

# Does the use an external db
external_db: false

# Uncomment the following line to adjust the SCC (not using CDK3/minishift)
adjust_scc: false